build.gradle
gradlew
gradlew.bat

chore : 스프링 시큐리티 추가
회원 파트에서 사용하는 스프링 시큐리티 라이브러리 추가했습니다.

[chore] : 스프링 시큐리티 추가

---

src/main/java/com/oreo/finalproject_5re5_be/project/entity/Project.java
src/main/java/com/oreo/finalproject_5re5_be/project/entity/ProjectStatus.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/User.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserCategory.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserChangeHistory.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserConnectionHistory.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserDelete.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserRoles.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserRolesCategory.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserState.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserTerms.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserTermsCondition.java
src/main/java/com/oreo/finalproject_5re5_be/user/entity/UserTermsHistory.java
src/main/resources/application.properties

유저와 프로젝트에서 사용하는 엔티티 정의했습니다.
추가적으로 "spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
" 변경했고 "@GeneratedValue(strategy = GenerationType.IDENTITY)"로 변경했습니다.

[chore] 유저 및 프로젝트 엔티티 정의 

---

src/main/java/com/oreo/finalproject_5re5_be/concat/entity/AudioFile.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatOption.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatRow.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatRowLog.java

- 복합키 제거
- OneToMany -> ManyToOne
- primitive variable -> wrapper variable 
- Boolean -> Character (Y/N)

[chore] concat 엔티티 수정

---

src/main/java/com/oreo/finalproject_5re5_be/tts/entity/Language.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/LanguageRepository.java
src/test/java/com/oreo/finalproject_5re5_be/tts/repository/LanguageRepositoryTest.java

Language Entity 수정
LanguageRepository 추가
LanguageRepositoryTest 추가

[feat] LanguageRepository 추가

---

src/main/java/com/oreo/finalproject_5re5_be/tts/entity/Style.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/StyleRepository.java
src/test/java/com/oreo/finalproject_5re5_be/tts/repository/StyleRepositoryTest.java

Style Entity 수정
StyleRepository 추가
StyleRepositoryTest 추가

[feat] StyleRepository 추가

---

.github/workflows/buildTest.yml
src/test/java/com/oreo/finalproject_5re5_be/FinalProject5Re5BeApplicationTests.java
src/test/java/com/oreo/finalproject_5re5_be/audio/AudioExtensionConverterTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/BeepMakerTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/SoundPlayerTest.java

- ci if문 삭제
- 테스트 h2환경으로 변경
- AudioExtensionConverterTest 경로문제로 test실패 -> 주석처리

[ci] CI 빌드 테스트 수정 및 test 환경 h2로 변경

---

src/main/java/com/oreo/finalproject_5re5_be/tts/entity/Voice.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/VoiceRepository.java
src/test/java/com/oreo/finalproject_5re5_be/tts/repository/VoiceRepositoryTest.java

Voice 엔티티 Lombok 애너테이션 수정
VoiceRepository 추가
VoiceRepositoryTest 추가

voice 엔티티 및 리포지토리

---

src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatTab.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/AudioFileRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatOptionRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatResultRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatRowLogRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatRowRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatTabLogRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatTabRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/MaterialAudioRepository.java

- 사용된 오디오 파일
- 병합 옵션
- 병합 결과 오디오
- 행 로그
- 행 상태
- 탭 로그
- 탭 상태
- 결과물에 사용된 오디오

[Feat] : Concat 리포지토리 추가

---

.gitignore

- .gitignore 파일을 수정하여 .json 파일을 무시하도록 설정했습니다.

[feat] .gitignore 파일  수정

---

src/main/resources/application-ndb-test.properties

- DB를 사용하지 않음에도 DB를 생성해서 테스트가 밀리는 이슈

[Chore] : DB를 사용하지 않는 테스트의 JPA 테이블 생성 이슈 해결

---

.github/workflows/buildTest.yml

[ci] CI EMAIL 환경변수 설정

---

src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberConfig.java
src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfig.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberNotFoundEmailException.java
src/main/java/com/oreo/finalproject_5re5_be/member/repository/MemberRepository.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImplTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImplTestByMock.java

- 스프링시큐리티 스웨거 접근 가능하게 만듦
- 이메일 전송 기능 구현 
> 참고 내용:
- 이메일 전송 기능 테스트는 Mockito 학습하고 추후에 작성해 놓겠습니다

[feat] 회원 이메일 인증 기능 구현

---

src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberConfig.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/ErrorResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberReadResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberNotFoundException.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImplTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImplTestByMock.java

- 핸들러에서 에러 정보 반환할 때 String으로 반환하는 부분 수정 ErrorResponse 사용
- 사용자의 회원 정보 일부만 조회하는 기능 
> 1. 참고 내용: 컨트롤러 Mockito 사용해서 테스트 할 때 주의점 
- 컨트롤러 Mockito로 테스트 하실 때 예외 반환 처리도 테스트 하고 싶으시면, 예외도 생성해서 반환하게 해줘야 합니다.
- 예를 들어서, 밑에와 같이 작성하셔야 합니다.
```java
// 올바른 사용 예시 코드 
MemberNotFoundException memberNotFoundException = new MemberNotFoundException();
when(memberService.read("qwerfde2312")).thenThrow(memberNotFoundException);
// 잘못된 사용 예시 코드(내부적으로 테스트 코드 상에 에러가 생길 확률이 높음)
when(memberService.read("qwerfde2312")).thenThrow(MemberNotFoundException.class);
```
> 2. 참고 내용: 에러코드 내용 객체 정의했습니다. 이 부분 같이 쓰면 좋을 것 같아요!
- 컨트롤러 단에서 예외 핸들링하시고 예외 내용을 반환할 때 단순 String이 아니라 ErrorResponse 사용하면 좋을 것 같습니다!
```java
// ErrorResponse 객체 정의(회원 파트에 정의됨)
@Getter
public class ErrorResponse {
private String message;
public …
```

[feat] 회원 단순 조회 기능 구현

---

src/main/java/com/oreo/finalproject_5re5_be/audio/dto/response/AudioFileInfo.java
src/main/java/com/oreo/finalproject_5re5_be/audio/service/AudioInfo.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java

- Audio Info length 타입 Long -> integer로 변경
- VcServiceImpl 삼항연산자 삭제

[chore] AudioInfo length Integer 타입으로 변경, 삼항연산자 삭제

---

src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberConfig.java
src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfig.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImplTest.java

> - HTTP 헤더를 이용하여 웹 애플리케이션에 대한 자원을 다른 출처에서 접근할 수 있도록 권한을 부여하는 정책.
> - 스프링 시큐리티에서 cors 설정을 따로 해두지 않아서 api 호출시 문제가 발생했습니다.이 부분 해결했습니다. 
> - 현재 "http://localhost:8080" 해당 url 로 가는 부분은 모두 cors error가 발생하지 않을 것입니다.
> - 밑에는 회원 파트 API 호출 성공 사진입니다.

[fix] 스프링 시큐리티 CORS 해결 

---

src/main/java/com/oreo/finalproject_5re5_be/audio/BeepMaker.java
src/test/java/com/oreo/finalproject_5re5_be/audio/BeepMakerTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/SoundPlayerTest.java

- 오디오 포맷을 파라미터로 받고, 포맷에 따라 모노, 스테레오로 생성하도록 변경
- interface로 변경 후 MonoBeepMaker, StereoBeepMaker로 분리 예정

[Refactor] 음성 생성 클래스 리팩토링

---

src/main/java/com/oreo/finalproject_5re5_be/audio/AudioResample.java
src/test/java/com/oreo/finalproject_5re5_be/audio/AudioResampleTest.java

- 각각의 오디오의 포맷을 일치시키는 기능
- 병합후 바이트 배열을 리샘플링

[Feat] 오디오 리샘플링

---

src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfig.java

- 모든 요청에 대해 작업 가능하도록 시큐리티 권한 열어 놨습니다!

[fix] 개발 단계에서 시큐리티 모든 요청 열어두기

---

build.gradle
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermsController.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberRegisterRequest.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberTermCheckOrNotRequest.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberTermRequest.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberTermUpdateRequest.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberTermConditionResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberTermConditionResponses.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberTermResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberTermResponses.java
src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberTerms.java
src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberTermsCondition.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberTermInvalidException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberTermsNotFoundException.java
src/main/java/com/oreo/finalproject_5re5_be/member/repository/MemberTermConditionRepository.java
src/main/java/com/oreo/finalproject_5re5_be/member/repository/MemberTermsRepository.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberTermsConditionServiceImpl.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberTermsServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfigTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermsControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/repository/MemberTermsRepositoryTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImplTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImplTestByMock.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberTermsConditionServiceImplTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/service/MemberTermsServiceImplTest.java

> - 회원 약관 구현
> - 추후에 리팩토링 하겠습니다!
> -

[feat] 회원 약관 구현

---

src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionController.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionControllerTest.java

[refactor] @Validated 어노테이션 추가 및 컨트롤러 테스트에서 불필요한 어노테이션 삭제

---

src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectService.java
src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImplTest.java

- memberSeq 받아 회원 조회로 변경
- test코드 추가

[test] projectService Test 코드 추가

---

src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java

[fix] File download 수정

---

src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberChangeHistory.java
src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberDelete.java
src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberRoles.java
src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberState.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java

[refactor] 회원 엔티티 코드 엔티티 참조하도록 변경

---

src/main/java/com/oreo/finalproject_5re5_be/global/constant/BatchProcessType.java
src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchInfo.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchRequest.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/TtsSentenceListDto.java
src/main/java/com/oreo/finalproject_5re5_be/tts/exception/TtsSentenceInValidInput.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/VoiceRepository.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceService.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/tts/controller/TtsControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceTest.java

[feat] TTS 현재상태 저장

---

build.gradle
src/main/java/com/oreo/finalproject_5re5_be/global/component/audio/AudioFormats.java
src/test/java/com/oreo/finalproject_5re5_be/audio/MonoConcatenatorTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/MonoIntervalConcatenatorTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/StereoConcatenatorTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/StereoIntervalConcatenatorTest.java

- 오디오 포맷 32비트 240, 441 Sampleate 포맷 추가
- 32비트 병합 테스트

[Feat] 오디오 포맷 32비트 추가

---

.github/workflows/buildTest.yml
build.gradle
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcSrcUrlRequest.java
src/main/java/com/oreo/finalproject_5re5_be/vc/exception/VcAPIFilesIsEmptyException.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcApiService.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcApiServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/vc/service/VcApiServiceImplTest.java

- VC API 활용 서비스단 생성
- VC 컨트롤러 적용

[Feat] VC API 활용 result 생성

---

src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcApiServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/vc/service/VcApiServiceImplTest.java

- 컨트롤러 for문 변경
- result 생성 경로 변경

[fix] Vc Result 생성 수정

---

src/main/java/com/oreo/finalproject_5re5_be/tts/controller/LanguageController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/LanguageDto.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/LanguageListDto.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/LanguageService.java
src/test/java/com/oreo/finalproject_5re5_be/tts/controller/LanguageControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/LanguageServiceTest.java

- 언어 목록 조회 응답 DTO 추가
- 언어 목록 조회 서비스 및 테스트 추가
- 언어 목록 조회 컨트롤러 및 테스트 추가
- #144

[Feat] 언어 목록 조회

---

.github/workflows/cdscript.yml

[ci] cd 구축

---

src/main/java/com/oreo/finalproject_5re5_be/global/exception/ErrorCode.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/CodeController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermsController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/advice/CodeExceptionHandler.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/advice/MemberExceptionHandler.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/CodeDuplicatedException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/CodeNotFoundException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberDuplicatedEmailException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberDuplicatedIdException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberInvalidTermConditionException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberMandatoryTermNotAgreedException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberNotFoundEmailException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberNotFoundException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberTermInvalidException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberTermsConditionNotFoundException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberTermsNotFoundException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberWrongCountTermCondition.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/RetryFailedException.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionControllerTest.java

> - 컨트롤러 코드 개선
> - 예외처리 어드바이스 활용

[refactor] 컨트롤러 코드 개선 및 예외처리 리팩토링

---

src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceService.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/tts/controller/TtsControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceTest.java

ttsSentence 로 생성하는 부분은 다른 테이블에서 관리하기 때문에 그대로 삭제하는 것으로 넣었습니다.

[feat] ttsSentence 삭제하기

---

.github/workflows/cdscript.yml

[CI] CD 구축 수정

---

src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/ConcatRowRequest.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/ConcatTabRequest.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/OriginAudioRequest.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/response/ConcatResultDetailsResponse.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/response/ConcatUrlResponse.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/AudioFile.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/AudioFormat.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatOption.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatResult.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatRowLog.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatTab.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatTabLog.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/MaterialAudio.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/AudioFileRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/AudioFormatRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/MaterialAudioRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/AudioFileService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/MaterialAudioService.java

- Material 관련 service와 레포지토리 추가
- AudioFile 관련 service와 레포지토리 추가
- 그 외 오타 수정, 엔티티 관계 매핑 수정

[fix] build 문제 해결하고 pr 올립니다

---

src/main/java/com/oreo/finalproject_5re5_be/global/config/SwaggerConfig.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/CodeController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermsController.java
src/main/java/com/oreo/finalproject_5re5_be/member/repository/MemberRepository.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/CodeControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermConditionControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermsControllerTest.java

> - 프론트랑 협업시 불필요한 API 호출 주석처리
> - 스웨거에서 로그인/로그아웃 테스트 할 수 있게 만듦
> - 불필요한 API 호출 주석 처리로 인해 기존에 작성한 테스트 코드 주석 처리

[refactor] 스웨거 개선 및 불필요한 API 호출 주석처리

---

src/main/java/com/oreo/finalproject_5re5_be/tts/controller/VoiceController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/VoiceDto.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/VoiceListDto.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/LanguageRepository.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/StyleRepository.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/VoiceRepository.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/VoiceService.java
src/test/java/com/oreo/finalproject_5re5_be/tts/controller/VoiceControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/repository/VoiceRepositoryFindTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/VoiceServiceTest.java

-  VoiceRepository에 언어, 스타일 정보로 조회하는 메서드 및 테스트 코드 추가
- 보이스 조회 응답 DTO 추가
- 보이스 조회 서비스 및 테스트 코드 추가
- 보이스 조회 컨트롤러 및 테스트 코드 추가
- #146

[Feat] 목소리 목록 조회

---

src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/AudioFormatRequest.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/ConcatResultRequest.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/response/ConcatResultDetailsResponse.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatResult.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/AudioFileRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatResultRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/MaterialAudioRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/AudioFileService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/AudioFormatService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/ConcatResultService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/MaterialAudioService.java

- AudioFormat, ConcatResult Service 새로 추가
- AudioFile, MaterialAudio Service 메서드 추가
- AudioFileRepository, MaterialAudioRepository 쿼리 메서드 추가 
- Dto 추가

[feat] Concat관련 Service 추가

---

.github/workflows/cdscript.yml

[ci] CD 구축 완료

---

src/main/java/com/oreo/finalproject_5re5_be/tts/controller/LanguageController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/controller/StyleController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/controller/VoiceController.java

- 보이스, 언어, 스타일 컨트롤러에 Swagger 어노테이션 추가
- TTS 생성 컨트롤러 메서드에 Swagger 어노테이션 추가
- close #174 
- close #175

[chore] : Swagger 어노테이션 추가

---

src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcAudioRequest.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcResultFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcText.java
src/main/java/com/oreo/finalproject_5re5_be/vc/repository/VcSrcFileRepository.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcApiServiceImpl.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcService.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java
src/main/resources/application.properties
src/test/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImplTest.java

- s3 File로 변경하고 컨트롤러에 우선 File을 MultipartFile로 변경
- length에서 지금 파일에서 길이를 못가지고 오는데 우선 vaild삭제
- JPQL삭제후 쿼리 메서드로 변경
- multipartfile이 swagger에서 동작되게 변경
- VC 행순서 자동 생성되게 변경

[fix] swagger에서 모두 동작되게 고침

---

src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/member/controller/MemberControllerTest.java

> - 회원 수정 처리 작업 리팩토링했습니다.
> - 스웨거에서 정상 처리 되는 것을 확인했습니다!

[refactor] 회원 수정 처리 작업 리팩토링

---

src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java

> - 프론트 API에서 추가해야할 기능 구현했습니다~

[feat] 회원 아이디 찾기 기능 추가

---

src/main/java/com/oreo/finalproject_5re5_be/global/exception/ErrorCode.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberChangePasswordRequest.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberReadResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberDuplicatedPasswordException.java
src/main/java/com/oreo/finalproject_5re5_be/member/exception/MemberTermsNotFoundException.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java

> - 프론트 API 명세서 보고 추가해야할 기능 구현했습니다~

[feat] 회원 비밀번호 변경 처리 구현

---

src/main/java/com/oreo/finalproject_5re5_be/code/controller/CodeController.java
src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberTermsController.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberTermConditionResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/dto/response/MemberTermsDetailResponse.java
src/main/java/com/oreo/finalproject_5re5_be/member/repository/MemberTermsRepository.java
src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberTermsServiceImpl.java

> - 프론트 측 API 명세서 참고해서 필요한 기능 구현했습니다
> - 1. 약관 내용 반환
> - ![image](https://github.com/user-attachments/assets/81f9aa3e-30b9-42b6-82ae-a34cb1c2ba58)
> - 2. 회원 탈퇴 사유 항목 카테고리 반환
> - ![image](https://github.com/user-attachments/assets/eb93a10d-eefa-4291-b595-88888ae353ff)

[refactor] 회원 약관 내용 반환, 회원 탈퇴 사유 항목 반환

---

src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
src/main/java/com/oreo/finalproject_5re5_be/global/component/audio/AudioFileTypeConverter.java
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java

- S3 서비스 메서드 분할
- File에서 MultipartFile로 변경 추가

[refactor] S3 refactoring 

---

src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcAudioRequest.java
src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcTextRequest.java
src/main/java/com/oreo/finalproject_5re5_be/vc/dto/response/VcResponse.java
src/main/java/com/oreo/finalproject_5re5_be/vc/dto/response/VcTextResponse.java
src/main/java/com/oreo/finalproject_5re5_be/vc/dto/response/VcUrlResponse.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcResultFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcSrcFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcText.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcTrgFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcHistoryServiceImpl.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcService.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java

- 정적 팩토리 메서드 패턴 사용
- VcResponse activate추가
- stream으로 변경
- VcResponse 병렬 처리 추가
- VcResponse rowOrder 순서대로 출력되게 변경

[refactor] vc service refactoring 

---

src/main/java/com/oreo/finalproject_5re5_be/global/exception/InValidValueException.java
src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchInfo.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchRequest.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/SentenceInfo.java
src/main/java/com/oreo/finalproject_5re5_be/tts/exception/DuplicatedSentenceException.java
src/main/java/com/oreo/finalproject_5re5_be/tts/exception/InValidRequestException.java
src/main/java/com/oreo/finalproject_5re5_be/tts/exception/ProjectMismatchException.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceService.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
src/main/java/com/oreo/finalproject_5re5_be/tts/util/TtsSentenceComparator.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestPatchSentenceOrder.java

- 예외 클래스 생성
- TTS 문장 Comparator
- 테스트
1. 정렬 순서 데이터가 존재하면 정렬 순서대로 정렬합니다.
2. 정렬 순서 데이터가 없으면 뒤로 보냅니다. 
3. 정렬 순서 데이터가 없으면 tsSeq (pk) 를 비교하여 정렬합니다. 
4. tsSeq(pk) 가 없으면 비교하지 않습니다.

[feat] TTS 문장 comparator  구현

---

src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcUrlRequest.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcResultFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcTrgFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcApiServiceImpl.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcHistoryService.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcHistoryServiceImpl.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcService.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImplTest.java

- VcTrgUrlRequest 추가
- VcSrcUrlRequest -> VcUrlRequest로 변경
- VcResponse에서 VcResultFile, Text 메서드로 뺌
- controller 변경
- trgFile, srcFile 파일 다운로드 service단으로 이동

[refactor] vcContoller refactor

---

src/main/java/com/oreo/finalproject_5re5_be/project/controller/ProjectController.java
src/main/java/com/oreo/finalproject_5re5_be/project/entity/Project.java
src/main/java/com/oreo/finalproject_5re5_be/project/exception/projectNotMemberException.java
src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectService.java
src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImplTest.java

- interface에 vaild가 설정이 안되어있어서 지정
- session잠시 지우고 1L 유저가 생성, 조회 할수 있게 변경
-  user_Seq -> member_Seq 수정 entity
- asctivate -> activate 수정 entity
- controller @SessionAttribute추가
- service 프로젝트의 회원 확인 추가

[fix] project vaild fix

---

src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/exception/VcNotMemberException.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcService.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java

- 컨트롤러 sessionAttribute 추가
- S3 서비스 삭제 부분 예외 로그로 변경
- VC API 생성 스프링 서버에 있는걸로 호출되게 변경

[feat] VCController 회원Session 값으로 회원확인

---

src/main/java/com/oreo/finalproject_5re5_be/concat/controller/AudioFileController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatMaterialController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatResultController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatRowController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatTabController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatWithBgmController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/ConcatResultDto.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/ConcatResultRequest.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/ConcatRowRequestDto.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/response/ConcatResultDetailsResponse.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatResult.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/MaterialAudio.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/ConcatResultRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/AudioMultipartFile.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/ConcatResultService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/ConcatRowService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/ConcatService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/MaterialAudioService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/concatenator/IntervalConcatenator.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/concatenator/MonoConcatenator.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/concatenator/MonoIntervalConcatenator.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/concatenator/StereoConcatenator.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/concatenator/StereoIntervalConcatenator.java
src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
src/test/java/com/oreo/finalproject_5re5_be/audio/MonoConcatenatorTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/MonoIntervalConcatenatorTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/StereoConcatenatorTest.java
src/test/java/com/oreo/finalproject_5re5_be/audio/StereoIntervalConcatenatorTest.java
src/test/java/com/oreo/finalproject_5re5_be/concat/repository/MaterialAudioRepositoryTest.java

- 재료 오디오 저장 조회
- ConcatResult 저장, 조회
- S3 Url 반환

[Feat] Concat 결과 생성, 조회

---

src/main/java/com/oreo/finalproject_5re5_be/FinalProject5Re5BeApplication.java
src/main/java/com/oreo/finalproject_5re5_be/global/config/AuditorAwareImpl.java
src/main/java/com/oreo/finalproject_5re5_be/global/config/JpaAuditingConfig.java
src/main/java/com/oreo/finalproject_5re5_be/global/entity/BaseEntity.java
src/main/java/com/oreo/finalproject_5re5_be/project/entity/Project.java
src/main/java/com/oreo/finalproject_5re5_be/tts/entity/SampleAudio.java
src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsAudioFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/Vc.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcRequestHistory.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcResultFile.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcResultHistory.java
src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcText.java

- 회원정보 찍히게 수정
- 수정, 수정자 찍히게 수정
- @PrePersist, @PreUpdate 엔티티들에게 부여
- JpaAuditing Bean 등록

[fix] baseEntity 동작 수정

---

src/main/java/com/oreo/finalproject_5re5_be/member/config/LoginAuthenticationFailureHandler.java
src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfig.java
src/test/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfigTest.java

[refactor] 로그인 실패시 401 에러 반환하게 만듦

---

src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java

[fix] VC SRC 행 생성 오류

---

.github/workflows/schedule-pr.yml

[fix] 스케줄러 작동 9시로 변경

---

src/main/java/com/oreo/finalproject_5re5_be/global/component/ByteArrayMultipartFile.java
src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
src/main/java/com/oreo/finalproject_5re5_be/tts/exception/SaveTtsMakeResultException.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/SaveTtsMakeResultService.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsMakeService.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/SaveTtsMakeResultTest.java

- tts 생성 서비스와 tts 생성 결과 저장 서비스 분리
- TTS 생성 결과 저장 서비스 테스트 코드 추가
- s3 파일 삭제 메서드 추가
- TTS 생성 결과 저장 실패 시 s3 파일 제거
- TTS 생성 실패 시 Failed 상태 저장
- close #194

[Feat] TTS 생성 실패 처리 추가

---

src/main/java/com/oreo/finalproject_5re5_be/concat/controller/AudioFileController.java

Daily PR: develop -> main

---

src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchRequest.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java

request body 에 getSortedSentenceList 라는 메서드를 사용하고 있었습니다.
그런데 getter 로 인식되어서 객체의 필드로 인식되는 것 같습니다.

[fix] swagger 에서 batchSave 엔드포인트의 request body 가 의도하지 않은 출력이 나오는 이슈

---

.github/workflows/cdscript.yml
.github/workflows/dockerdeploy.yml
.github/workflows/schedule-pr.yml
Dockerfile
docker-compose.yml
src/main/resources/application.properties

- docker로 서버 배포 
- 무중단 배포는 아직 못함.

[CI] docker 배포로 변경

---

src/main/java/com/oreo/finalproject_5re5_be/global/constant/BatchProcessType.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchInfo.java
src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/TtsSentenceListDto.java
src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsProgressStatus.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/TtsSentenceRepository.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
src/test/java/com/oreo/finalproject_5re5_be/tts/repository/TtsSentenceRepositoryTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestGetSentenceList.java

- 정렬 순서를 기준으로 정렬해서 출력되도록 변경
- DELETE 타입 추가 (TTS 행 삭제 가능)

TTS batch delete 기능 추가

---

src/main/java/com/oreo/finalproject_5re5_be/tts/controller/StyleController.java
src/main/java/com/oreo/finalproject_5re5_be/tts/repository/StyleRepository.java
src/main/java/com/oreo/finalproject_5re5_be/tts/service/StyleService.java
src/test/java/com/oreo/finalproject_5re5_be/tts/controller/StyleControllerTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/repository/StyleRepositoryTest.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/StyleServiceTest.java

- 언어 코드로 voice가 있는 style만 조회하는 API 구현
- close #258

[Feat] 언어 코드로 voice가 있는 style만 조회하는 API 구현

---

src/main/java/com/oreo/finalproject_5re5_be/project/controller/ProjectController.java

- @SessionAttributte는 파라미터로 들어가서 @AuthenticationPrincipal사용

[fix] 회원 인증 @AuthenticationPrincipal로 변경

---

src/main/java/com/oreo/finalproject_5re5_be/member/config/LoginAuthenticationSuccessHandler.java
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcService.java
src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java

- Text저장 @RequestBody VcTextRequest로 변경
- VcTextRequest로 변경

[Fix]vc controller request 변경

---

src/main/java/com/oreo/finalproject_5re5_be/global/config/SwaggerConfig.java

[fix] 스웨거 설정 수정

---

src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/SentenceInfo.java
src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java

- SentenceInfo에서 styleSeq 제거 및 테스트 코드 변경

[Fix] SentenceInfo에서 styleSeq 제거

---

.github/workflows/dockerdeploy.yml

[fix] : githubactions cicd env 추가

---

src/main/java/com/oreo/finalproject_5re5_be/project/controller/ProjectController.java
src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java

[fix] : AuthenticationPrincipal를 session으로 변경

---

src/main/java/com/oreo/finalproject_5re5_be/global/config/WebConfig.java

[fix] WebConfig 설정 변경하기

---

src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatMaterialController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatWithBgmController.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/ConcatResponseDto.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/ConcatResultRequest.java
src/main/java/com/oreo/finalproject_5re5_be/concat/dto/response/ConcatResultResponse.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/BgmFile.java
src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatResult.java
src/main/java/com/oreo/finalproject_5re5_be/concat/repository/BgmFileRepository.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/ConcatResultService.java
src/main/java/com/oreo/finalproject_5re5_be/concat/service/MaterialAudioService.java

- 어떤 audioFile이 쓰였는지 조회하는 메서드에서 어떤 bgm파일이 쓰였고, 어떤 audio파일이 쓰였는지 조회하는 메서드로 수정 
- 컨트롤러가 수정됨에 따라 다른 service와 dto 등 수정

[feat] 결과물에 어떤 오디오파일이 쓰였는지 조회하는 메서드 수정
